### ISSUE TITLE
Spoko to wygląda, propozycja paru usprawnień

### ISSUE THREAD

**Issue by spiechu** [wnnawalaniec/phlambda#1]
1. Nie potrzebujesz `composer.lock`.
2. W pliku `.travis.yml` możesz testować wobec PHP 8.0 i 8.1 żeby upewnić się, że działa tu i tu. Tak samo na niskich i wysokich zależnościach.
3. Możesz dodać `.gitattributes` i wyciąć rzeczy niepotrzebne zaciągającym paczkę (np. testy), coś jak https://github.com/symfony/framework-bundle/blob/5.4/.gitattributes
4. Pomyśl nad licencją MIT, bo GPL uniemożliwi zaciąganie paczki w komercyjnych projektach ze względu na "wirusowość" licencji GPL.

**Comment by wnnawalaniec** [comment]
Dzięki za uwagi. Nie zwracałem na to nawet uwagi, a każda wydaje się mieć uzasadnienie :D
